//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Categoria = new HashSet<Categoria>();
            this.Relacion = new HashSet<Relacion>();
            this.Relacion1 = new HashSet<Relacion>();
            this.ValorAtributo = new HashSet<ValorAtributo>();
        }
    
        public int Id { get; set; }
        public int Sku { get; set; }
        public Nullable<long> Gtin { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] Thumbnail { get; set; }
    
        public virtual ICollection<Categoria> Categoria { get; set; }
        public virtual ICollection<Relacion> Relacion { get; set; }
        public virtual ICollection<Relacion> Relacion1 { get; set; }
        public virtual ICollection<ValorAtributo> ValorAtributo { get; set; }
    }
}
